# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\School_Project\Resume Search\ui\resumesearcher_v2.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1015, 970)
        MainWindow.setMinimumSize(QtCore.QSize(1015, 970))
        MainWindow.setMaximumSize(QtCore.QSize(1015, 970))
        MainWindow.setWindowTitle("ResuSearch - поиск и фильтрация резюме")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color:rgb(213, 213, 213);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.peopletableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.peopletableWidget.setGeometry(QtCore.QRect(9, 50, 1001, 691))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.peopletableWidget.setFont(font)
        self.peopletableWidget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.peopletableWidget.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.peopletableWidget.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.peopletableWidget.setLineWidth(1)
        self.peopletableWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.peopletableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.peopletableWidget.setAutoScroll(True)
        self.peopletableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.peopletableWidget.setAlternatingRowColors(False)
        self.peopletableWidget.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.peopletableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.peopletableWidget.setTextElideMode(QtCore.Qt.ElideRight)
        self.peopletableWidget.setShowGrid(True)
        self.peopletableWidget.setGridStyle(QtCore.Qt.SolidLine)
        self.peopletableWidget.setWordWrap(True)
        self.peopletableWidget.setCornerButtonEnabled(False)
        self.peopletableWidget.setObjectName("peopletableWidget")
        self.peopletableWidget.setColumnCount(5)
        self.peopletableWidget.setRowCount(28)
        item = QtWidgets.QTableWidgetItem()
        item.setText("1")
        self.peopletableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.peopletableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.peopletableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.peopletableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.peopletableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setText("Имя")
        self.peopletableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setText("Фамилия")
        self.peopletableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setText("Должность")
        self.peopletableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setText("Возраст")
        self.peopletableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setText("Уровень образования")
        self.peopletableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.peopletableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.peopletableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.peopletableWidget.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.peopletableWidget.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.peopletableWidget.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.peopletableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.peopletableWidget.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.peopletableWidget.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.peopletableWidget.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.peopletableWidget.setItem(1, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.peopletableWidget.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.peopletableWidget.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.peopletableWidget.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.peopletableWidget.setItem(2, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.peopletableWidget.setItem(2, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.peopletableWidget.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.peopletableWidget.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.peopletableWidget.setItem(3, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.peopletableWidget.setItem(3, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.peopletableWidget.setItem(3, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.peopletableWidget.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.peopletableWidget.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.peopletableWidget.setItem(4, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.peopletableWidget.setItem(4, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.peopletableWidget.setItem(4, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.peopletableWidget.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.peopletableWidget.setItem(5, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.peopletableWidget.setItem(5, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.peopletableWidget.setItem(5, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.peopletableWidget.setItem(5, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.peopletableWidget.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.peopletableWidget.setItem(6, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.peopletableWidget.setItem(6, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.peopletableWidget.setItem(6, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.peopletableWidget.setItem(6, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.peopletableWidget.setItem(7, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.peopletableWidget.setItem(7, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.peopletableWidget.setItem(7, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.peopletableWidget.setItem(7, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.peopletableWidget.setItem(7, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.peopletableWidget.setItem(8, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.peopletableWidget.setItem(8, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.peopletableWidget.setItem(8, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.peopletableWidget.setItem(8, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.peopletableWidget.setItem(8, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.peopletableWidget.setItem(9, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.peopletableWidget.setItem(9, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.peopletableWidget.setItem(9, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.peopletableWidget.setItem(9, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.peopletableWidget.setItem(9, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.peopletableWidget.setItem(10, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.peopletableWidget.setItem(10, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.peopletableWidget.setItem(10, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.peopletableWidget.setItem(10, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.peopletableWidget.setItem(10, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.peopletableWidget.setItem(11, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.peopletableWidget.setItem(11, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.peopletableWidget.setItem(11, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.peopletableWidget.setItem(11, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.peopletableWidget.setItem(11, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.peopletableWidget.setItem(12, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.peopletableWidget.setItem(12, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.peopletableWidget.setItem(12, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.peopletableWidget.setItem(12, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.peopletableWidget.setItem(12, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.peopletableWidget.setItem(13, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.peopletableWidget.setItem(13, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.peopletableWidget.setItem(13, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.peopletableWidget.setItem(13, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.peopletableWidget.setItem(13, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.peopletableWidget.setItem(14, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.peopletableWidget.setItem(14, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.peopletableWidget.setItem(14, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.peopletableWidget.setItem(14, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.peopletableWidget.setItem(14, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.peopletableWidget.setItem(15, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.peopletableWidget.setItem(15, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.peopletableWidget.setItem(15, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.peopletableWidget.setItem(15, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.peopletableWidget.setItem(15, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.peopletableWidget.setItem(16, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.peopletableWidget.setItem(16, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.peopletableWidget.setItem(16, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.peopletableWidget.setItem(16, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.peopletableWidget.setItem(16, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.peopletableWidget.setItem(17, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.peopletableWidget.setItem(17, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.peopletableWidget.setItem(17, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.peopletableWidget.setItem(17, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.peopletableWidget.setItem(17, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.peopletableWidget.setItem(18, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.peopletableWidget.setItem(18, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.peopletableWidget.setItem(18, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.peopletableWidget.setItem(18, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.peopletableWidget.setItem(18, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.peopletableWidget.setItem(19, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.peopletableWidget.setItem(19, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.peopletableWidget.setItem(19, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.peopletableWidget.setItem(19, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.peopletableWidget.setItem(19, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.peopletableWidget.setItem(20, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.peopletableWidget.setItem(20, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.peopletableWidget.setItem(20, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.peopletableWidget.setItem(20, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.peopletableWidget.setItem(20, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.peopletableWidget.setItem(21, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.peopletableWidget.setItem(21, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.peopletableWidget.setItem(21, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.peopletableWidget.setItem(21, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.peopletableWidget.setItem(21, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.peopletableWidget.setItem(22, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.peopletableWidget.setItem(22, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.peopletableWidget.setItem(22, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.peopletableWidget.setItem(22, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.peopletableWidget.setItem(22, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.peopletableWidget.setItem(23, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.peopletableWidget.setItem(23, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.peopletableWidget.setItem(23, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.peopletableWidget.setItem(23, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.peopletableWidget.setItem(23, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.peopletableWidget.setItem(24, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.peopletableWidget.setItem(24, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.peopletableWidget.setItem(24, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.peopletableWidget.setItem(24, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.peopletableWidget.setItem(24, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.peopletableWidget.setItem(25, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.peopletableWidget.setItem(25, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.peopletableWidget.setItem(25, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.peopletableWidget.setItem(25, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.peopletableWidget.setItem(25, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.peopletableWidget.setItem(26, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.peopletableWidget.setItem(26, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.peopletableWidget.setItem(26, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.peopletableWidget.setItem(26, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.peopletableWidget.setItem(26, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.peopletableWidget.setItem(27, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.peopletableWidget.setItem(27, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.peopletableWidget.setItem(27, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.peopletableWidget.setItem(27, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.peopletableWidget.setItem(27, 4, item)
        self.peopletableWidget.horizontalHeader().setVisible(True)
        self.peopletableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.peopletableWidget.horizontalHeader().setDefaultSectionSize(100)
        self.peopletableWidget.horizontalHeader().setMinimumSectionSize(20)
        self.peopletableWidget.horizontalHeader().setStretchLastSection(True)
        self.peopletableWidget.verticalHeader().setVisible(False)
        self.peopletableWidget.verticalHeader().setDefaultSectionSize(21)
        self.editresumeButton = QtWidgets.QPushButton(self.centralwidget)
        self.editresumeButton.setGeometry(QtCore.QRect(10, 760, 480, 80))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.editresumeButton.setFont(font)
        self.editresumeButton.setStyleSheet("background-color: rgb(75, 75, 75);\n"
"color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(175, 175, 175);")
        self.editresumeButton.setText("Просмотреть/Редактировать резюме")
        self.editresumeButton.setObjectName("editresumeButton")
        self.deleteButton = QtWidgets.QPushButton(self.centralwidget)
        self.deleteButton.setGeometry(QtCore.QRect(520, 760, 480, 80))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.deleteButton.setFont(font)
        self.deleteButton.setStyleSheet("background-color: rgb(75, 75, 75);\n"
"color: rgb(255, 255, 255);\n"
"selection-color: rgb(255, 255, 255);")
        self.deleteButton.setText("Удалить резюме")
        self.deleteButton.setObjectName("deleteButton")
        self.excelexportButton = QtWidgets.QPushButton(self.centralwidget)
        self.excelexportButton.setGeometry(QtCore.QRect(10, 860, 1000, 100))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.excelexportButton.setFont(font)
        self.excelexportButton.setStyleSheet("background-color: rgb(75, 75, 75);\n"
"color: rgb(255, 255, 255);\n"
"selection-color: rgb(255, 255, 255);")
        self.excelexportButton.setText("Экспортировать в таблицу Microsoft Excel")
        self.excelexportButton.setObjectName("excelexportButton")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(700, 10, 261, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.setItemText(0, "")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(470, 10, 221, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        self.peopletableWidget.setSortingEnabled(True)
        item = self.peopletableWidget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.peopletableWidget.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.peopletableWidget.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.peopletableWidget.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "New Row"))
        __sortingEnabled = self.peopletableWidget.isSortingEnabled()
        self.peopletableWidget.setSortingEnabled(False)
        item = self.peopletableWidget.item(0, 0)
        item.setText(_translate("MainWindow", "ц"))
        item = self.peopletableWidget.item(0, 1)
        item.setText(_translate("MainWindow", "ц"))
        item = self.peopletableWidget.item(0, 2)
        item.setText(_translate("MainWindow", "ц"))
        item = self.peopletableWidget.item(0, 3)
        item.setText(_translate("MainWindow", "ц"))
        item = self.peopletableWidget.item(0, 4)
        item.setText(_translate("MainWindow", "ц"))
        item = self.peopletableWidget.item(1, 0)
        item.setText(_translate("MainWindow", "ц"))
        item = self.peopletableWidget.item(1, 1)
        item.setText(_translate("MainWindow", "ц"))
        item = self.peopletableWidget.item(1, 2)
        item.setText(_translate("MainWindow", "ц"))
        item = self.peopletableWidget.item(1, 3)
        item.setText(_translate("MainWindow", "ц"))
        item = self.peopletableWidget.item(1, 4)
        item.setText(_translate("MainWindow", "ц"))
        item = self.peopletableWidget.item(2, 0)
        item.setText(_translate("MainWindow", "ц"))
        item = self.peopletableWidget.item(2, 1)
        item.setText(_translate("MainWindow", "ц"))
        item = self.peopletableWidget.item(2, 2)
        item.setText(_translate("MainWindow", "ц"))
        item = self.peopletableWidget.item(2, 3)
        item.setText(_translate("MainWindow", "ц"))
        item = self.peopletableWidget.item(2, 4)
        item.setText(_translate("MainWindow", "ц"))
        item = self.peopletableWidget.item(3, 0)
        item.setText(_translate("MainWindow", "ц"))
        item = self.peopletableWidget.item(3, 1)
        item.setText(_translate("MainWindow", "ц"))
        item = self.peopletableWidget.item(3, 2)
        item.setText(_translate("MainWindow", "ц"))
        item = self.peopletableWidget.item(3, 3)
        item.setText(_translate("MainWindow", "ц"))
        item = self.peopletableWidget.item(3, 4)
        item.setText(_translate("MainWindow", "ц"))
        item = self.peopletableWidget.item(4, 0)
        item.setText(_translate("MainWindow", "ц"))
        item = self.peopletableWidget.item(4, 1)
        item.setText(_translate("MainWindow", "ц"))
        item = self.peopletableWidget.item(4, 2)
        item.setText(_translate("MainWindow", "ц"))
        item = self.peopletableWidget.item(4, 3)
        item.setText(_translate("MainWindow", "ц"))
        item = self.peopletableWidget.item(4, 4)
        item.setText(_translate("MainWindow", "ц"))
        item = self.peopletableWidget.item(5, 0)
        item.setText(_translate("MainWindow", "ц"))
        item = self.peopletableWidget.item(5, 1)
        item.setText(_translate("MainWindow", "ц"))
        item = self.peopletableWidget.item(5, 2)
        item.setText(_translate("MainWindow", "ц"))
        item = self.peopletableWidget.item(5, 3)
        item.setText(_translate("MainWindow", "ц"))
        item = self.peopletableWidget.item(5, 4)
        item.setText(_translate("MainWindow", "ц"))
        item = self.peopletableWidget.item(6, 0)
        item.setText(_translate("MainWindow", "ц"))
        item = self.peopletableWidget.item(6, 1)
        item.setText(_translate("MainWindow", "ц"))
        item = self.peopletableWidget.item(6, 2)
        item.setText(_translate("MainWindow", "ц"))
        item = self.peopletableWidget.item(6, 3)
        item.setText(_translate("MainWindow", "ц"))
        item = self.peopletableWidget.item(6, 4)
        item.setText(_translate("MainWindow", "ц"))
        item = self.peopletableWidget.item(7, 0)
        item.setText(_translate("MainWindow", "ц"))
        item = self.peopletableWidget.item(7, 1)
        item.setText(_translate("MainWindow", "ц"))
        item = self.peopletableWidget.item(7, 2)
        item.setText(_translate("MainWindow", "ц"))
        item = self.peopletableWidget.item(7, 3)
        item.setText(_translate("MainWindow", "ц"))
        item = self.peopletableWidget.item(7, 4)
        item.setText(_translate("MainWindow", "ц"))
        item = self.peopletableWidget.item(8, 0)
        item.setText(_translate("MainWindow", "ц"))
        item = self.peopletableWidget.item(8, 1)
        item.setText(_translate("MainWindow", "ц"))
        item = self.peopletableWidget.item(8, 2)
        item.setText(_translate("MainWindow", "ц"))
        item = self.peopletableWidget.item(8, 3)
        item.setText(_translate("MainWindow", "ц"))
        item = self.peopletableWidget.item(8, 4)
        item.setText(_translate("MainWindow", "ц"))
        item = self.peopletableWidget.item(9, 0)
        item.setText(_translate("MainWindow", "ц"))
        item = self.peopletableWidget.item(9, 1)
        item.setText(_translate("MainWindow", "ц"))
        item = self.peopletableWidget.item(9, 2)
        item.setText(_translate("MainWindow", "ц"))
        item = self.peopletableWidget.item(9, 3)
        item.setText(_translate("MainWindow", "ц"))
        item = self.peopletableWidget.item(9, 4)
        item.setText(_translate("MainWindow", "ц"))
        item = self.peopletableWidget.item(10, 0)
        item.setText(_translate("MainWindow", "ц"))
        item = self.peopletableWidget.item(10, 1)
        item.setText(_translate("MainWindow", "ц"))
        item = self.peopletableWidget.item(10, 2)
        item.setText(_translate("MainWindow", "ц"))
        item = self.peopletableWidget.item(10, 3)
        item.setText(_translate("MainWindow", "ц"))
        item = self.peopletableWidget.item(10, 4)
        item.setText(_translate("MainWindow", "ц"))
        item = self.peopletableWidget.item(11, 0)
        item.setText(_translate("MainWindow", "ц"))
        item = self.peopletableWidget.item(11, 1)
        item.setText(_translate("MainWindow", "ц"))
        item = self.peopletableWidget.item(11, 2)
        item.setText(_translate("MainWindow", "ц"))
        item = self.peopletableWidget.item(11, 3)
        item.setText(_translate("MainWindow", "ц"))
        item = self.peopletableWidget.item(11, 4)
        item.setText(_translate("MainWindow", "ц"))
        item = self.peopletableWidget.item(12, 0)
        item.setText(_translate("MainWindow", "ц"))
        item = self.peopletableWidget.item(12, 1)
        item.setText(_translate("MainWindow", "ц"))
        item = self.peopletableWidget.item(12, 2)
        item.setText(_translate("MainWindow", "ц"))
        item = self.peopletableWidget.item(12, 3)
        item.setText(_translate("MainWindow", "ц"))
        item = self.peopletableWidget.item(12, 4)
        item.setText(_translate("MainWindow", "ц"))
        item = self.peopletableWidget.item(13, 0)
        item.setText(_translate("MainWindow", "ц"))
        item = self.peopletableWidget.item(13, 1)
        item.setText(_translate("MainWindow", "ц"))
        item = self.peopletableWidget.item(13, 2)
        item.setText(_translate("MainWindow", "ц"))
        item = self.peopletableWidget.item(13, 3)
        item.setText(_translate("MainWindow", "ц"))
        item = self.peopletableWidget.item(13, 4)
        item.setText(_translate("MainWindow", "ц"))
        item = self.peopletableWidget.item(14, 0)
        item.setText(_translate("MainWindow", "ц"))
        item = self.peopletableWidget.item(14, 1)
        item.setText(_translate("MainWindow", "ц"))
        item = self.peopletableWidget.item(14, 2)
        item.setText(_translate("MainWindow", "ц"))
        item = self.peopletableWidget.item(14, 3)
        item.setText(_translate("MainWindow", "ц"))
        item = self.peopletableWidget.item(14, 4)
        item.setText(_translate("MainWindow", "ц"))
        item = self.peopletableWidget.item(15, 0)
        item.setText(_translate("MainWindow", "ц"))
        item = self.peopletableWidget.item(15, 1)
        item.setText(_translate("MainWindow", "ц"))
        item = self.peopletableWidget.item(15, 2)
        item.setText(_translate("MainWindow", "ц"))
        item = self.peopletableWidget.item(15, 3)
        item.setText(_translate("MainWindow", "ц"))
        item = self.peopletableWidget.item(15, 4)
        item.setText(_translate("MainWindow", "ц"))
        item = self.peopletableWidget.item(16, 0)
        item.setText(_translate("MainWindow", "ц"))
        item = self.peopletableWidget.item(16, 1)
        item.setText(_translate("MainWindow", "ц"))
        item = self.peopletableWidget.item(16, 2)
        item.setText(_translate("MainWindow", "ц"))
        item = self.peopletableWidget.item(16, 3)
        item.setText(_translate("MainWindow", "ц"))
        item = self.peopletableWidget.item(16, 4)
        item.setText(_translate("MainWindow", "ц"))
        item = self.peopletableWidget.item(17, 0)
        item.setText(_translate("MainWindow", "ц"))
        item = self.peopletableWidget.item(17, 1)
        item.setText(_translate("MainWindow", "ц"))
        item = self.peopletableWidget.item(17, 2)
        item.setText(_translate("MainWindow", "ц"))
        item = self.peopletableWidget.item(17, 3)
        item.setText(_translate("MainWindow", "ц"))
        item = self.peopletableWidget.item(17, 4)
        item.setText(_translate("MainWindow", "ц"))
        item = self.peopletableWidget.item(18, 0)
        item.setText(_translate("MainWindow", "ц"))
        item = self.peopletableWidget.item(18, 1)
        item.setText(_translate("MainWindow", "ц"))
        item = self.peopletableWidget.item(18, 2)
        item.setText(_translate("MainWindow", "ц"))
        item = self.peopletableWidget.item(18, 3)
        item.setText(_translate("MainWindow", "ц"))
        item = self.peopletableWidget.item(18, 4)
        item.setText(_translate("MainWindow", "ц"))
        item = self.peopletableWidget.item(19, 0)
        item.setText(_translate("MainWindow", "ц"))
        item = self.peopletableWidget.item(19, 1)
        item.setText(_translate("MainWindow", "ц"))
        item = self.peopletableWidget.item(19, 2)
        item.setText(_translate("MainWindow", "ц"))
        item = self.peopletableWidget.item(19, 3)
        item.setText(_translate("MainWindow", "ц"))
        item = self.peopletableWidget.item(19, 4)
        item.setText(_translate("MainWindow", "ц"))
        item = self.peopletableWidget.item(20, 0)
        item.setText(_translate("MainWindow", "ц"))
        item = self.peopletableWidget.item(20, 1)
        item.setText(_translate("MainWindow", "ц"))
        item = self.peopletableWidget.item(20, 2)
        item.setText(_translate("MainWindow", "ц"))
        item = self.peopletableWidget.item(20, 3)
        item.setText(_translate("MainWindow", "ц"))
        item = self.peopletableWidget.item(20, 4)
        item.setText(_translate("MainWindow", "ц"))
        item = self.peopletableWidget.item(21, 0)
        item.setText(_translate("MainWindow", "ц"))
        item = self.peopletableWidget.item(21, 1)
        item.setText(_translate("MainWindow", "ц"))
        item = self.peopletableWidget.item(21, 2)
        item.setText(_translate("MainWindow", "ц"))
        item = self.peopletableWidget.item(21, 3)
        item.setText(_translate("MainWindow", "ц"))
        item = self.peopletableWidget.item(21, 4)
        item.setText(_translate("MainWindow", "ц"))
        item = self.peopletableWidget.item(22, 0)
        item.setText(_translate("MainWindow", "ц"))
        item = self.peopletableWidget.item(22, 1)
        item.setText(_translate("MainWindow", "ц"))
        item = self.peopletableWidget.item(22, 2)
        item.setText(_translate("MainWindow", "ц"))
        item = self.peopletableWidget.item(22, 3)
        item.setText(_translate("MainWindow", "ц"))
        item = self.peopletableWidget.item(22, 4)
        item.setText(_translate("MainWindow", "ц"))
        item = self.peopletableWidget.item(23, 0)
        item.setText(_translate("MainWindow", "ц"))
        item = self.peopletableWidget.item(23, 1)
        item.setText(_translate("MainWindow", "ц"))
        item = self.peopletableWidget.item(23, 2)
        item.setText(_translate("MainWindow", "ц"))
        item = self.peopletableWidget.item(23, 3)
        item.setText(_translate("MainWindow", "ц"))
        item = self.peopletableWidget.item(23, 4)
        item.setText(_translate("MainWindow", "ц"))
        item = self.peopletableWidget.item(24, 0)
        item.setText(_translate("MainWindow", "ц"))
        item = self.peopletableWidget.item(24, 1)
        item.setText(_translate("MainWindow", "ц"))
        item = self.peopletableWidget.item(24, 2)
        item.setText(_translate("MainWindow", "ц"))
        item = self.peopletableWidget.item(24, 3)
        item.setText(_translate("MainWindow", "ц"))
        item = self.peopletableWidget.item(24, 4)
        item.setText(_translate("MainWindow", "ц"))
        item = self.peopletableWidget.item(25, 0)
        item.setText(_translate("MainWindow", "ц"))
        item = self.peopletableWidget.item(25, 1)
        item.setText(_translate("MainWindow", "ц"))
        item = self.peopletableWidget.item(25, 2)
        item.setText(_translate("MainWindow", "ц"))
        item = self.peopletableWidget.item(25, 3)
        item.setText(_translate("MainWindow", "ц"))
        item = self.peopletableWidget.item(25, 4)
        item.setText(_translate("MainWindow", "ц"))
        item = self.peopletableWidget.item(26, 0)
        item.setText(_translate("MainWindow", "ц"))
        item = self.peopletableWidget.item(26, 1)
        item.setText(_translate("MainWindow", "ц"))
        item = self.peopletableWidget.item(26, 2)
        item.setText(_translate("MainWindow", "ц"))
        item = self.peopletableWidget.item(26, 3)
        item.setText(_translate("MainWindow", "ц"))
        item = self.peopletableWidget.item(26, 4)
        item.setText(_translate("MainWindow", "ц"))
        item = self.peopletableWidget.item(27, 0)
        item.setText(_translate("MainWindow", "ц"))
        item = self.peopletableWidget.item(27, 1)
        item.setText(_translate("MainWindow", "ц"))
        item = self.peopletableWidget.item(27, 2)
        item.setText(_translate("MainWindow", "ц"))
        item = self.peopletableWidget.item(27, 3)
        item.setText(_translate("MainWindow", "ц"))
        item = self.peopletableWidget.item(27, 4)
        item.setText(_translate("MainWindow", "ц"))
        self.peopletableWidget.setSortingEnabled(__sortingEnabled)
        self.label.setText(_translate("MainWindow", "Выделить по профессии"))
